[project]
name = "lanms-backend"
version = "3.0.0a9"
requires-python = ">=3.12,<3.13"
dependencies = [
    "alembic~=1.13.1",
    "fastapi[standard]~=0.115.0",
    "pydantic[email]~=2.7.1",
    "pydantic-extra-types~=2.8.0",
    "requests~=2.32.1",
    "psycopg2-binary~=2.9.9",
    "sentry-sdk[fastapi,sqlalchemy,starlette]~=2.8.0",
    "sqlalchemy~=2.0.30",
    "pyjwt[crypto]~=2.8.0",
    "pyotp~=2.9.0",
    "passlib~=1.7.4",
    "bcrypt~=4.1.3",
    "pandas~=2.2.2",
    "fastapi-pagination~=0.12.31",
    "fastapi-filter[sqlalchemy]~=2.0.0",
    "sendgrid~=6.11.0",
    "python-dotenv~=1.0.1",
    "tunsberg~=0.1.4",
    "phonenumbers~=8.13.48",
    "postmarker~=1.0.0",
]

[dependency-groups]
dev = [
    "pre-commit~=3.5.0",
    "ruff~=0.4.4",
]

[tool.uv]
package = false

[tool.ruff]
line-length = 160
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "alembic",
]

[tool.ruff.lint]
select = [
    "RUF", # ruff
    "E", "W", # pycodestyle
    "F", # Pyflakes
    "UP", # pyupgrade
    "B", # flake8-bugbear
    "SIM", # flake8-simplify
    "I", # isort
    "T", # flake8-print
    "TD", # flake8-todos
    "LOG", # flake8-logging
    "N", # pep8-naming
    "D", # pydocstyle
    "RET", # flake8-return
    "TYP", # flake8-type-checking
    "PL", # pylint
]
ignore = [
    "D100", # Missing docstring in public module
    "D104", # Missing docstring in public package
    "D415", # First line should end with a period
    "D203", # 1 blank line required before class docstring
    "D212", # Multi-line docstring summary should start at the first line
    "D400", # First line should end with a period
    "TD003", # Missing issue link on the line following
    "B008", # Do not perform function calls in argument defaults
]


[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true
