"""Initial db

Revision ID: ddb42266651d
Revises:
Create Date: 2024-12-15 14:09:22.373005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb42266651d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('phone_code', sa.String(length=12), nullable=True, comment='Phone number with country code, e.g. +47'),
    sa.Column('phone_number', sa.String(length=32), nullable=True, comment='Phone number with country code, e.g. 99887766'),
    sa.Column('referrer', sa.String(), nullable=True, comment='Who/what referred this user'),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('privacy_policy_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('terms_of_service_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('phone_code', 'phone_number', name='_phone_code_phone_number_uc')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('otp')
    # ### end Alembic commands ###
