"""empty message

Revision ID: e74e37cb846e
Revises: 3c54be1b70e2
Create Date: 2026-04-16 16:59:40.238953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e74e37cb846e'
down_revision: Union[str, None] = '3c54be1b70e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'articles', ['id'])
    op.create_unique_constraint(None, 'event_interests', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_interests', type_='unique')
    op.drop_constraint(None, 'articles', type_='unique')
    # ### end Alembic commands ###
